### ISSUE TITLE
Does not work for Webpack 5?

### ISSUE THREAD

**Issue by larryspace** [heiseshandian/dynamic-alias-resolve-plugin#1]

**Comment by heiseshandian** [comment]
Yes, currently it does not support Webpack 5, I will support it this weekend.

**Comment by heiseshandian** [comment]
Hi, @larryspace , I have released a new version of this plugin to support webpack5, and there is a working example for webpack5, [examples/webpack5](https://github.com/heiseshandian/dynamic-alias-resolve-plugin/tree/master/examples/webpack5). If you have any other problems, please feel free to ask me. Thanks.
